#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
================================================================================
 run06_cascade.py -- the inelastic cascade: phi phi -> h -> hh -> 4 phi
================================================================================
Connects H3 to the GGV multiplicity language.  The published GGV 2 -> 2N
multiplicity (JHEP 01 (2022) 146,
arXiv:2110.14673; toolbox arXiv:2207.11277) is generated by graviton EXCHANGE
(the effective four-scalar vertex) with no h^3 insertion; H3 opens an
ADDITIONAL inelastic channel:

    phi phi --(H_int)--> h --(H3, NEW)--> h h --(H_int)--> (phi phi)(phi phi).

This script simulates exactly that cascade on a mixed graviton + scalar
register and states the structural fact (verified as an exact superselection in code):
the DERIVED H3 is what OPENS the four-scalar channel -- H_int alone
conserves Q = N_phi + 2 N_h, forbidding N_phi = 4 -- and quantifies the
absolute yield and its g~_3 dependence at the GR-fixed structure.

Register (all l = 2, away from the gauge-special l = 0, 1):
  gravitons b: (2,0), (2,+-1), (2,+-2)   [5 modes]
  scalars   a: (2,0), (2,+-1)            [3 modes]
  per-mode cutoff d = 3, total dim 3^8 = 6561; evolution done exactly inside
  the Lz = 0 block (both H3 and H_int conserve Lz by the operator-level rule).
Initial state: two scalars (2,1)+(2,-1) (N_phi = 2, N_h = 0, Lz = 0).

Outputs:
  fig_F1_cascade.pdf    sector populations <N_h>(t), <N_phi>(t), and
                        P(N_phi = 4)(t) with H3 on vs off.
  fig_F2_yield.pdf      four-scalar yield vs g~_3 at fixed matter coupling,
                        with d = 4 truncation overlay.
  summary_cascade.json  quotable on/off yield ratios, truncation deviations.

Runtime: full ~15-40 min (d = 4 overlay is the slow part); QUICK ~2 min.
================================================================================
"""
import numpy as np
import matplotlib.pyplot as plt

from nhq import model as md
from nhq.util import Timer, save_json, save_npz, save_fig, QUICK, \
    INK, RUST, TEAL, GOLD, GREY, PALETTE

G_UNIT = 1.0
GM_REP = 12.0        # matter coupling g~_m (same reduced-units convention)
G3_REP = 12.0        # graviton self-coupling g~_3
T_FIT = 20.0         # snapshot time for the F3 coupling power-law fits

G_MODES = [(2, 0), (2, 1), (2, -1), (2, 2), (2, -2)]
S_MODES = [(2, 0), (2, 1), (2, -1)]


def build(d, g3, gm, lz=0):
    basis, n_g = md.FockBasis.mixed(G_MODES, S_MODES, d=d, lz=lz)
    g_tab = md.cubic_vertex_table(G_MODES, g_eff=g3 * G_UNIT)
    m_tab = md.matter_vertex_table(G_MODES, S_MODES, g_m=gm * G_UNIT)
    H = basis.H_mixed(g_tab, m_tab, n_g)
    return basis, n_g, H


def initial_state(basis, n_g):
    occ0 = [0] * basis.M
    occ0[n_g + S_MODES.index((2, 1))] = 1
    occ0[n_g + S_MODES.index((2, -1))] = 1
    occ0 = tuple(occ0)
    psi0 = np.zeros(basis.dim, complex)
    psi0[basis.index[occ0]] = 1.0
    return psi0, occ0


def main():
    summary = {"channel": "phi phi -> h (H_int) -> hh (H3) -> 4 phi (H_int).",
               "framing": "With H3 OFF the four-scalar yield vanishes "
               "IDENTICALLY: H_int = b\u2020aa + h.c. conserves the charge "
               "Q = N_phi + 2 N_h, so N_phi = 4 is superselected away from "
               "the N_phi = 2 initial state.  The honest statement is that "
               "the derived H3 OPENS this channel (a selection-rule fact), "
               "and the quantitative content is the absolute yield and its "
               "g~_3 dependence -- NOT an on/off 'enhancement ratio'."}
    d = 3

    # ---------------- F0: cubic-resonance audit of the boost spectrum -----
    with Timer("F0: resonance audit of omega_l = sqrt(l^2+l+1)"):
        # Gaunt(l1,l2,l3; 0,0,0) != 0 iff parity (l1+l2+l3 even) and triangle
        # hold, so every parity+triangle-allowed triad supports the vertex.
        # Asymptotically omega_l = (l+1/2) + 3/(8(l+1/2)) + ..., hence for the
        # closest allowed triad l3 = l1 + l2 the mismatch
        # omega_{l1}+omega_{l2}-omega_{l3} -> 1/2 from above: the near-horizon
        # boost spectrum is CUBIC-RESONANCE-FREE with a uniform gap >= ~1/2.
        # This is why all H3/H_int inelasticity here is virtual (off-shell),
        # why the yields obey the perturbative power laws tested in F3, and
        # (mechanistically) why the quench in run02 need not thermalise.
        lmax = 16
        triads = []
        for l1 in range(2, lmax + 1):
            for l2 in range(l1, lmax + 1):
                for l3 in range(2, lmax + 1):
                    if (l1 + l2 + l3) % 2 or not abs(l1 - l2) <= l3 <= l1 + l2:
                        continue
                    dw = abs(md.omega_l(l3) - md.omega_l(l1) - md.omega_l(l2))
                    triads.append((dw, l1, l2, l3))
        triads.sort()
        summary["F0_min_mismatch"] = triads[0][0]
        summary["F0_closest_triads"] = [dict(dw=t[0], l1=t[1], l2=t[2],
                                             l3=t[3]) for t in triads[:5]]
        summary["F0_statement"] = ("no near-resonant Gaunt-allowed cubic "
                                   "triad exists; min |domega| = "
                                   f"{triads[0][0]:.4f} for l <= {lmax}, "
                                   "approaching the asymptotic bound 1/2")
        print(f"  min |omega3 - omega1 - omega2| over allowed triads "
              f"(l <= {lmax}): {triads[0][0]:.4f} at "
              f"({triads[0][1]},{triads[0][2]})->{triads[0][3]}; "
              "asymptotic bound = 1/2")

    # ---------------- F1: cascade on/off ----------------------------------
    with Timer(f"F1: cascade dynamics d={d}, Lz=0 block"):
        basis, n_g, H_on = build(d, G3_REP, GM_REP)
        _, _, H_off = build(d, 0.0, GM_REP)
        print(f"  mixed register: {basis.M} modes, Lz=0 block dim = "
              f"{basis.dim}")
        summary["F1_block_dim"] = basis.dim
        # conservation sanity, recorded
        Lz = np.diag(basis.Lz_diag())
        summary["F1_commHLz"] = float(np.abs(H_on @ Lz - Lz @ H_on).max())
        # the superselection charge Q = N_phi + 2 N_h of the H3-off model:
        Q = np.diag(np.array([sum(o[s] for s in range(n_g, basis.M)) +
                              2 * sum(o[s] for s in range(n_g))
                              for o in basis.occs], dtype=float))
        summary["F1_commHoff_Q"] = float(np.abs(H_off @ Q - Q @ H_off).max())
        summary["F1_commHon_Q"] = float(np.abs(H_on @ Q - Q @ H_on).max())
        psi0, occ0 = initial_state(basis, n_g)
        g_idx = list(range(n_g))
        s_idx = list(range(n_g, basis.M))
        ts = np.linspace(0, 40, 21 if QUICK else 81)
        ev_on = md.BlockEvolver(H_on)
        ev_off = md.BlockEvolver(H_off)
        Nh, Nphi, P4, P4_off = [], [], [], []
        Ns_diag = {}
        for lab, occs in (("h", g_idx), ("phi", s_idx)):
            Ns_diag[lab] = np.array([sum(o[s] for s in occs)
                                     for o in basis.occs])
        for t in ts:
            for tag, ev in (("on", ev_on), ("off", ev_off)):
                psi = ev.psi(psi0, t)
                pr = np.abs(psi) ** 2
                if tag == "on":
                    Nh.append(float(np.dot(pr, Ns_diag["h"])))
                    Nphi.append(float(np.dot(pr, Ns_diag["phi"])))
                    P4.append(float(pr[Ns_diag["phi"] == 4].sum()))
                else:
                    P4_off.append(float(pr[Ns_diag["phi"] == 4].sum()))
        summary["F1_P4_max_on"] = float(np.max(P4))
        summary["F1_P4_max_off"] = float(np.max(P4_off))
        # (no on/off 'ratio' is quoted: the off value is an exact zero by the
        #  Q-superselection recorded above; see summary['framing'])

        fig, axes = plt.subplots(1, 2, figsize=(7.0, 2.9))
        axes[0].plot(ts, Nh, color=INK, label=r"$\langle N_h\rangle$")
        axes[0].plot(ts, Nphi, color=TEAL, label=r"$\langle N_\phi\rangle$")
        axes[0].set_xlabel("$t$")
        axes[0].set_ylabel("sector occupation")
        axes[0].set_title(rf"cascade populations, $\tilde g_3={G3_REP:g}$, "
                          rf"$\tilde g_m={GM_REP:g}$")
        axes[0].legend()
        axes[1].plot(ts, P4, color=RUST, label=r"$H_3$ on")
        axes[1].plot(ts, P4_off, "--", color=GREY, label=r"$H_3$ off")
        axes[1].set_xlabel("$t$")
        axes[1].set_ylabel(r"$P(N_\phi = 4)$")
        axes[1].set_title("four-scalar yield: the new channel")
        axes[1].legend()
        fig.subplots_adjust(wspace=0.3)  # gap
        save_fig(fig, "fig_F1_cascade.pdf")
        save_npz("data_F1_cascade.npz", ts=ts, Nh=np.array(Nh),
                 Nphi=np.array(Nphi), P4=np.array(P4),
                 P4_off=np.array(P4_off))

    # ---------------- F2: yield vs g~_3, truncation overlay ---------------
    # Single snapshot time per (d, g~_3), so the Krylov evolver is the right
    # instrument: it needs only the sparse action of H, NOT a full
    # eigendecomposition.  The basis and the Nphi=4 projector are built ONCE
    # per d (they do not depend on g~_3); only H is rebuilt as g~_3 sweeps.
    # Diagonalising the 6464-dimensional dense block once per coupling instead
    # would dominate the runtime of the whole script.
    with Timer("F2: four-scalar yield vs g~_3 (+ d=4 overlay, Krylov)"):
        g3s = np.linspace(0, 15, 6 if QUICK else 16)
        t_snap = 20.0
        yields = {}
        d_list = (3,) if QUICK else (3, 4)
        for dd in d_list:
            basis, n_g = md.FockBasis.mixed(G_MODES, S_MODES, d=dd, lz=0)
            g_unit = md.cubic_vertex_table(G_MODES, g_eff=1.0)
            m_tab = md.matter_vertex_table(G_MODES, S_MODES,
                                           g_m=GM_REP * G_UNIT)
            psi0d, _ = initial_state(basis, n_g)
            s_idx = list(range(n_g, basis.M))
            mask4 = np.array([sum(o[s] for s in s_idx) == 4
                              for o in basis.occs])
            print(f"    d={dd}: block dim={basis.dim} (Krylov, {len(g3s)} "
                  "couplings x 1 snapshot)")
            ys = []
            for g3 in g3s:
                g_tab = {k: (g3 * G_UNIT) * v for k, v in g_unit.items()}
                H = basis.H_mixed(g_tab, m_tab, n_g)
                psi = md.evolve_krylov(H, psi0d, t_snap)
                ys.append(float((np.abs(psi) ** 2)[mask4].sum()))
            yields[dd] = np.array(ys)
        if len(d_list) > 1:
            # truncation deviation compared on the shared coupling grid
            summary["F2_trunc_dev"] = float(np.max(np.abs(
                yields[d_list[0]] - yields[d_list[-1]])))
        summary["F2_yield_at_grep"] = float(
            yields[d_list[0]][np.argmin(np.abs(g3s - G3_REP))])

        fig, ax = plt.subplots(figsize=(4.2, 3.0))
        for dd, c in zip(d_list, (INK, RUST)):
            ax.plot(g3s, yields[dd], "o-" if dd == d_list[0] else "--", ms=3,
                    color=c, label=f"$d={dd}$")
        ax.set_xlabel(r"graviton self-coupling $\tilde g_3$")
        ax.set_ylabel(rf"$P(N_\phi=4)$ at $t={t_snap:g}$")
        ax.set_title(rf"the $H_3$ channel opens the $2\to4$ scalar yield "
                     rf"($\tilde g_m={GM_REP:g}$)")
        ax.legend()
        save_fig(fig, "fig_F2_yield.pdf")
        save_npz("data_F2_yield.npz", g3=g3s,
                 **{f"yield_d{dd}": yields[dd] for dd in d_list})

    # ---------------- F3: pre-registered perturbative power laws ----------
    # Minimal path to N_phi = 4 requires exactly ONE H3 insertion (the only
    # Q-violating operator, Delta Q = +-2) and THREE H_int insertions:
    # 4th-order amplitude  A ~ g~_m^3 g~_3 t^4/4! (1 + O(t)),  hence the
    # PRE-REGISTERED predictions   P4 ~ g~_3^2  (any g~_m, linear response
    # in H3),   P4 ~ g~_m^6  (small g~_m),   P4 ~ t^8  (short time).
    # Each is tested as a log-log slope; deviations mark the breakdown of
    # perturbation theory (recorded, also quotable).
    with Timer("F3: power-law slope tests (predict 2, 6, 8)"):
        basis, n_g = md.FockBasis.mixed(G_MODES, S_MODES, d=d, lz=0)
        g_unit = md.cubic_vertex_table(G_MODES, g_eff=1.0)
        m_unit = md.matter_vertex_table(G_MODES, S_MODES, g_m=1.0)

        def H_of(g3, gm):
            return basis.H_mixed({k: g3 * v for k, v in g_unit.items()},
                                 {k: gm * v for k, v in m_unit.items()}, n_g)

        psi0f, _ = initial_state(basis, n_g)
        Nphi_diag = np.array([sum(o[s] for s in range(n_g, basis.M))
                              for o in basis.occs])
        mask4 = (Nphi_diag == 4)

        def P4_of(g3, gm, t):
            psi = md.BlockEvolver(H_of(g3, gm)).psi(psi0f, t)
            return float((np.abs(psi) ** 2)[mask4].sum())

        npts = 4 if QUICK else 7
        fits = {}
        # (a) P4 vs g~_3 at strong g~_m (linear response in H3): slope 2
        g3s = np.logspace(-2, -0.5, npts)
        p_g3 = np.array([P4_of(g3, GM_REP, T_FIT) for g3 in g3s])
        fits["slope_g3"] = float(np.polyfit(np.log(g3s), np.log(p_g3), 1)[0])
        # (b) P4 vs g~_m at small couplings: slope 6
        gms = np.logspace(-1, 0, npts)
        p_gm = np.array([P4_of(1.0, gm, T_FIT) for gm in gms])
        fits["slope_gm"] = float(np.polyfit(np.log(gms), np.log(p_gm), 1)[0])
        # (c) P4 vs t at short time, physical couplings: slope 8
        tss = np.logspace(np.log10(0.05), np.log10(0.4), npts)
        ev = md.BlockEvolver(H_of(G3_REP, GM_REP))
        p_t = np.array([float((np.abs(ev.psi(psi0f, t)) ** 2)[mask4].sum())
                        for t in tss])
        fits["slope_t"] = float(np.polyfit(np.log(tss), np.log(p_t), 1)[0])
        fits["predicted"] = dict(slope_g3=2, slope_gm=6, slope_t=8)
        summary["F3_powerlaws"] = fits
        print(f"  fitted slopes: g~_3 -> {fits['slope_g3']:.3f} (predict 2), "
              f"g~_m -> {fits['slope_gm']:.3f} (predict 6), "
              f"t -> {fits['slope_t']:.3f} (predict 8)")

        fig, axes = plt.subplots(1, 3, figsize=(9.6, 2.8))
        for ax, (x, y, s, lab, pred) in zip(axes, [
                (g3s, p_g3, fits["slope_g3"], r"$\tilde g_3$", 2),
                (gms, p_gm, fits["slope_gm"], r"$\tilde g_m$", 6),
                (tss, p_t, fits["slope_t"], "$t$", 8)]):
            ax.loglog(x, y, "o", ms=4, color=INK)
            ax.loglog(x, y[0] * (x / x[0]) ** pred, "--", color=RUST,
                      label=f"predicted slope {pred}")
            ax.set_xlabel(lab)
            ax.set_ylabel(r"$P(N_\phi=4)$")
            ax.set_title(f"fit {s:.2f}")
            ax.legend(fontsize=7)
        fig.suptitle("pre-registered 4th-order power laws "
                     "(one $H_3$ + three $H_{\\rm int}$ insertions)", y=1.04)
        fig.subplots_adjust(wspace=0.4, top=0.87)  # gap + room for suptitle
        save_fig(fig, "fig_F3_powerlaws.pdf")

    save_json("summary_cascade.json", summary)
    print("\nrun06 complete.")


if __name__ == "__main__":
    main()
